<template>
  <q-page>
    <page-header> </page-header>

    <div class="row">
      <div class="col-sm-12 col-md-4">
        <my-table
          title="Employees"
          :loading="loading"
          :data="data"
          :columns="columns"
          row-key="id"
          :pagination.sync="pager"
          :filter="filter"
          @request="fetch"
        >
          <template #body-cell-avatar="props">
            <q-td>
              <user-avatar :value="props.row" size="sm" />
            </q-td>
          </template>
          <template #body-cell-actions2="props">
            <q-td :class="{ selected: sid === props.row.id }">
              <q-btn
                flat
                round
                icon="las la-hand-point-right"
                @click="sid = props.row.id"
                :color="sid === props.row.id ? 'positive' : ''"
              />
            </q-td>
          </template>
        </my-table>
      </div>
      <div class="col-sm-12 col-md-8 q-pa-sm">
        <q-card v-if="user && user.id" flat bordered>
          <q-toolbar>
            <user-avatar :value="user" size="lg" />
            <q-toolbar-title>
              {{ user.displayName || user.userName }}'s commission types config
              <q-item-label caption>
                {{ user.email }} / {{ user.phone }}
              </q-item-label>
            </q-toolbar-title>
            <AddCommissionTypeBtn @added="added" :userId="user.id" />
          </q-toolbar>
          <q-card-section class="row">
            <div style="flex:auto" class="q-pa-sm">
              <q-markup-table dense flat>
                <thead>
                  <tr>
                    <th class="text-left">Actions</th>
                    <th class="text-left">Code</th>
                    <th class="text-left">Description</th>
                    <th class="text-left">Rp / Value</th>
                    <th class="text-left">AutoGenerated</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="item in dataConfigs" :key="item.id">
                    <td class="text-left">
                      <div style="margin-bottom:12px;">
                        <q-btn
                          flat
                          round
                          color="secondary"
                          icon="las la-save"
                          :disable="loading"
                          @click="update(item)"
                        >
                          <q-tooltip content-class="secondary">
                            Update line config
                          </q-tooltip>
                        </q-btn>
                        <q-btn
                          v-if="!item.autoGenerated"
                          flat
                          round
                          color="negative"
                          icon="las la-trash"
                          :disable="loading || item.autoGenerated"
                          @click="del(item)"
                        >
                          <q-tooltip content-class="negative">
                            Delete line config
                          </q-tooltip>
                        </q-btn>
                      </div>
                    </td>
                    <td class="text-left text-bold">
                      <q-input
                        dense
                        outlined
                        v-model="item.code"
                        name="code"
                        v-validate="'required|max:25'"
                        :error="errors.has('code')"
                        :error-message="errors.first('code')"
                        :readonly="loading || item.autoGenerated"
                      />
                    </td>
                    <td class="text-left">
                      <q-input
                        dense
                        outlined
                        v-model="item.description"
                        name="description"
                        v-validate="'max:255'"
                        :error="errors.has('description')"
                        :error-message="errors.first('description')"
                        :readonly="loading"
                      />
                    </td>
                    <td class="text-left">
                      <money-field
                        dense
                        outlined
                        v-model="item.moneyPerValue"
                        name="moneyField"
                        v-validate="'required|min:0'"
                        :error="errors.has('moneyField')"
                        :error-message="errors.first('moneyField')"
                        :readonly="loading"
                      />
                    </td>
                    <td>
                      <div style="margin-bottom:12px;">
                        {{ item.autoGenerated ? "YES" : "NO" }}
                      </div>
                    </td>
                  </tr>
                </tbody>
              </q-markup-table>
            </div>
          </q-card-section>
        </q-card>
      </div>
    </div>

    <!-- commission history -->
    <hr />
    <q-toolbar v-if="user && user.id">
      <user-avatar :value="user" size="lg" />
      <q-toolbar-title>
        {{ user.displayName || user.userName }}'s commission monthly report
        <q-item-label caption>
          {{ user.email }} / {{ user.phone }}
        </q-item-label>
      </q-toolbar-title>
    </q-toolbar>
    <UserCommissions :user="user" v-if="user && user.id" />
  </q-page>
</template>

<script>
import AddCommissionTypeBtn from "./components/AddCommissionTypeBtn";
import UserCommissions from "./components/UserCommissions";
export default {
  components: {
    AddCommissionTypeBtn,
    UserCommissions
  },
  data() {
    return {
      sid: undefined,
      loading: false,
      data: [],
      columns: [
        {
          name: "actions2",
          label: "action",
          field: "action",
          width: "25px",
          align: "center"
        },
        {
          name: "avatar",
          label: "Avatar",
          field: "avatar",
          align: "center"
        },
        {
          name: "userName",
          label: "Name",
          field: "userName",
          align: "left",
          format: (val, row) =>
            row.displayName && row.displayName !== null ? row.displayName : val
        },
        {
          name: "roleName",
          label: "Role",
          field: "roleName",
          align: "left"
        },
        {
          name: "Notes",
          label: "Notes",
          field: "notes",
          align: "left"
        }
      ],
      pager: {
        page: 1,
        rowsPerPage: 15,
        rowsNumber: 0
      },
      filter: undefined,
      dataConfigs: []
    };
  },
  computed: {
    user() {
      if (!this.sid) return undefined;
      return this.data.find(x => x.id === this.sid);
    }
  },
  watch: {
    user(val) {
      this.fetchConfig();
    }
  },
  mounted() {
    this.fetch();
  },
  methods: {
    async fetchConfig() {
      let val = this.user;
      if (!val || !val.id) {
        return;
      }
      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.getByUser(val.id);
        this.dataConfigs = res.data;
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    },
    async fetch(pager) {
      if (this.loading) return;
      this.loading = true;
      pager = pager?.pagination || this.pager;

      try {
        var res = await this.$api.users.get(pager);
        var dt = res.data;
        this.data = dt.rows.map(x => x);

        this.columns = this.columns.map(x => {
          return Object.assign({}, x, {
            sortable: dt.sortColumns.indexOf(x.field.toLowerCase()) > -1
          });
        });

        this.pager.rowsNumber = dt.rowsNumber;
        this.pager.page = dt.page;
        this.pager.sortBy = dt.sortBy;
        this.pager.descending = dt.descending;
        this.pager.rowsPerPage = dt.rowsPerPage;
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    },
    added(model) {
      this.dataConfigs.push(model);
    },
    async update(model) {
      if (!(await this.$validator.validateAll())) {
        this.$toastr.error("Please complete the form then resubmit");
        return;
      }

      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.put(model);
        this.$toastr.success("Record was updated");
        this.dataConfigs = this.dataConfigs.map(x =>
          x.id === model.id ? model : x
        );
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    },
    async del(model) {
      if (!confirm(`Are you sure want to delete ${model.code} record?`)) return;
      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.delete(model.id);
        this.$toastr.success("Record was deleted");
        this.dataConfigs = this.dataConfigs.filter(x => x.id !== model.id);
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    }
  }
};
</script>
<style lang="scss" scoped>
.selected {
  border-left: 5px solid var(--q-color-positive);
}
</style>
