<template>
  <div>
    <q-btn flat round icon="las la-plus" @click="model = true">
      <q-tooltip content-class="bg-primary">
        Add new commission type for selected user
      </q-tooltip>
    </q-btn>
    <q-dialog v-model="model" persistent>
      <q-card>
        <dialog-header title="Add Commission Type" />
        <q-card-section v-if="model">
          <q-form @submit="submit">
            <q-input
              label="Code"
              dense
              outlined
              v-model="modelInput.code"
              name="code"
              v-validate="'required|max:25'"
              :error="errors.has('code')"
              :error-message="errors.first('code')"
              :readonly="loading || modelInput.autoGenerated"
              autofocus
            />
            <q-input
              label="Description"
              dense
              outlined
              v-model="modelInput.description"
              name="description"
              v-validate="'max:255'"
              :error="errors.has('description')"
              :error-message="errors.first('description')"
              :readonly="loading"
            />
            <money-field
              label="Rp / Value"
              dense
              outlined
              v-model="modelInput.moneyPerValue"
              name="moneyField"
              v-validate="'required|min_value:0'"
              :error="errors.has('moneyField')"
              :error-message="errors.first('moneyField')"
              :readonly="loading"
            />

            <submit-button :loading="loading" class="full-width">
              Submit
            </submit-button>
          </q-form>
        </q-card-section>
      </q-card>
    </q-dialog>
  </div>
</template>
<script>
export default {
  props: {
    userId: {
      type: String,
      default: () => undefined
    }
  },
  data() {
    return {
      loading: false,
      modelInput: {},
      model: false
    };
  },
  computed: {},
  methods: {
    async submit() {
      if (!this.userId) return;
      if (!(await this.$validator.validateAll())) {
        this.$toastr.error("Please complete the form then resubmit");
        return;
      }
      if (this.loading) return;
      this.loading = true;
      try {
        this.modelInput.userId = this.userId;
        let res = await this.$api.commissionTypes.post(this.modelInput);
        this.$toastr.success("Record was added");
        this.$emit("added", res.data);
        this.modelInput = {};
        this.model = false;
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    }
  }
};
</script>
