<template>
  <div v-if="user && user.id">
    <q-btn flat round icon="las la-cog" @click="model = true" />
    <q-dialog v-model="model" full-width>
      <q-card v-if="user && user.id" flat bordered>
        <q-toolbar>
          <user-avatar :value="user" size="lg" />
          <q-toolbar-title>
            {{ user.displayName || user.userName }}'s commission types config
            <q-item-label caption>
              {{ user.email }} / {{ user.phone }}
            </q-item-label>
          </q-toolbar-title>
          <AddCommissionTypeBtn @added="added" :userId="user.id" />
          <q-btn flat round icon="las la-times" v-close-popup />
        </q-toolbar>
        <q-card-section class="row">
          <div style="flex:auto" class="q-pa-sm">
            <q-markup-table dense flat>
              <thead>
                <tr>
                  <th class="text-left">Actions</th>
                  <th class="text-left">Code</th>
                  <th class="text-left">Description</th>
                  <th class="text-left">Rp / Value</th>
                  <th class="text-left">AutoGenerated</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in dataConfigs" :key="item.id">
                  <td class="text-left">
                    <div style="margin-bottom:12px;">
                      <q-btn
                        flat
                        round
                        color="secondary"
                        icon="las la-save"
                        :disable="loading"
                        @click="update(item)"
                      >
                        <q-tooltip content-class="secondary">
                          Update line config
                        </q-tooltip>
                      </q-btn>
                      <q-btn
                        v-if="!item.autoGenerated"
                        flat
                        round
                        color="negative"
                        icon="las la-trash"
                        :disable="loading || item.autoGenerated"
                        @click="del(item)"
                      >
                        <q-tooltip content-class="negative">
                          Delete line config
                        </q-tooltip>
                      </q-btn>
                    </div>
                  </td>
                  <td class="text-left text-bold">
                    <q-input
                      dense
                      outlined
                      v-model="item.code"
                      name="code"
                      v-validate="'required|max:25'"
                      :error="errors.has('code')"
                      :error-message="errors.first('code')"
                      :readonly="loading || item.autoGenerated"
                    />
                  </td>
                  <td class="text-left">
                    <q-input
                      dense
                      outlined
                      v-model="item.description"
                      name="description"
                      v-validate="'max:255'"
                      :error="errors.has('description')"
                      :error-message="errors.first('description')"
                      :readonly="loading"
                    />
                  </td>
                  <td class="text-left">
                    <money-field
                      dense
                      outlined
                      v-model="item.moneyPerValue"
                      name="moneyField"
                      v-validate="'required|min_value:0'"
                      :error="errors.has('moneyField')"
                      :error-message="errors.first('moneyField')"
                      :readonly="loading"
                    />
                  </td>
                  <td>
                    <div style="margin-bottom:12px;">
                      {{ item.autoGenerated ? "YES" : "NO" }}
                    </div>
                  </td>
                </tr>
              </tbody>
            </q-markup-table>
          </div>
        </q-card-section>
      </q-card>
    </q-dialog>
  </div>
</template>
<script>
import AddCommissionTypeBtn from "./AddCommissionTypeBtn";
export default {
  name: "UserCommissionConfigBtn",
  props: {
    user: {
      type: Object,
      default: () => {}
    }
  },
  components: {
    AddCommissionTypeBtn
  },
  data() {
    return {
      loading: false,
      model: false,
      dataConfigs: []
    };
  },
  watch: {
    "user.id"() {
      this.fetchConfig();
    }
  },
  mounted(){
    this.fetchConfig()
  },
  methods: {
    async fetchConfig() {
      let val = this.user;
      if (!val || !val.id) {
        return;
      }
      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.getByUser(val.id);
        this.dataConfigs = res.data;
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    },
    added(model) {
      this.dataConfigs.push(model);
    },
    async update(model) {
      if (!(await this.$validator.validateAll())) {
        this.$toastr.error("Please complete the form then resubmit");
        return;
      }

      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.put(model);
        this.$toastr.success("Record was updated");
        this.dataConfigs = this.dataConfigs.map(x =>
          x.id === model.id ? model : x
        );
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    },
    async del(model) {
      if (!confirm(`Are you sure want to delete ${model.code} record?`)) return;
      if (this.loading) return;
      this.loading = true;
      try {
        var res = await this.$api.commissionTypes.delete(model.id);
        this.$toastr.success("Record was deleted");
        this.dataConfigs = this.dataConfigs.filter(x => x.id !== model.id);
      } catch (e) {
        this.$toastr.error(e);
      }
      this.loading = false;
    }
  }
};
</script>
